#!/bin/bash
#PBS -W group_list=ericlyons
#PBS -q windfall
#PBS -l select=1:ncpus=16:mem=32gb
#PBS -l place=pack:shared
#PBS -l walltime=01:00:00
#PBS -l cput=01:00:00

module load unsupported
module load ferng/glibc
export CCTOOLS_HOME=/home/u12/cosi/cctools-7.0.19-x86_64-centos7
export PATH=${CCTOOLS_HOME}/bin:$PATH

cd /home/u12/cosi/cosi-workers
/home/u12/cosi/cctools-7.0.19-x86_64-centos7/bin/work_queue_factory  128.196.142.81 6000 -T local -w 50
